### ISSUE TITLE
AttributeError: module 'delegator' has no attribute 'run'

### ISSUE THREAD

**Issue by sherifrad** [kennethreitz/white#1]
When i tried to run 
`
white fx_check.py
`
i got this error:

`$ white fx_check.py
Traceback (most recent call last):
  File "/home/sherif/miniconda3/bin/white", line 11, in <module>
    load_entry_point('white==0.0.1', 'console_scripts', 'white')()
  File "/home/sherif/miniconda3/lib/python3.6/site-packages/white-0.0.1-py3.6.egg/white.py", line 20, in main
    c = delegator.run(
AttributeError: module 'delegator' has no attribute 'run'
`

but if i run `black fx_check.py` it worked well

**Comment by kennethreitz** [comment]
try latest version :)

**Comment by kennethreitz** [comment]
v0.1.0
